name: PullRequest

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ~1.18

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p _local/bin
        cd go
        CGO_ENABLED=0 go build -o ../_local/bin/logs ./cmd/logs/
      shell: bash